version: '3.8'

services:
  booklibrary-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - booklibrary-network

networks:
  booklibrary-network:
    driver: bridge